#默认使用配置
spring:
  profiles:
    active: dev
  datasource:
    name: caifeng
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://www.fenfeijituan.com:3308/caifeng?characterEncoding=utf-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: caifeng
    password: caifeng
    driver-class-name: com.mysql.jdbc.Driver
  data:
    mongodb:
      uri:  mongodb://mongodb数据库的用户名:mongodb的密码@139.9.155.149:27017/?authSource=caifeng
      database: caifeng
#  redis:
#    host: 139.9.155.149
#    port: 6379
#    pass:
#    database: 0
#    maxIdle: 300
#    maxWait: 3000
#    testOnBorrow: true

#公共配置与profiles选择无关
mybatis:
  #  mapperScanPackage: com.cf.mapper
  #  typeAliasesPackage: com.cf.pojo
  mapperLocations: classpath:com.cf.sms.dao.mapper/*.xml
  configLocation: classpath:config/SqlMapConfig.xml
